name: Compile LaTeX and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy static files to public directory
        run: |
          mkdir -p public
          cp frontend/** public/

      - name: Inject build date into HTML
        run: sed -i "s|<!-- BUILD_DATE -->|$(TZ='Europe/Sarajevo' date '+%-d.%-m.%Y.')|g" public/index.html

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: >-
            -pdf
            -synctex=1
            -interaction=nonstopmode
            -file-line-error
            -aux-directory=./out
            -output-directory=.
            -jobname=Silabus
            -shell-escape

      - name: Copy PDF to frontend directory
        run: cp Silabus.pdf public/

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
